run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive

issues:
  exclude-use-default: false
